### ISSUE TITLE
Back to default tab on rerender

### ISSUE THREAD

**Issue by WimVanDerZijden** [marcuslindfeldt/react-web-tabs#1]
When there is a state change in a parent component,  the tab jumps back to the default tab.

**Comment by jeysinghanbu** [comment]
@WimVanDerZijden Did  you get solution for this.

**Comment by Flydiverny** [comment]
Can you provide a reproducible example?

**Comment by Flydiverny** [comment]
Seems like this reproduces the issue you are having:
https://codesandbox.io/s/j7w4nxzw0y

**Comment by MathiasKoch** [comment]
:+1: 
I am experiencing the same issue, still without a fix or even a workaround :(

**Comment by MathiasKoch** [comment]
Can be 'remedied' by removing defaultTab prop from Tabs component

**Comment by Flydiverny** [comment]
I'll see if I can have a look at it in the coming days :)

**Comment by Flydiverny** [comment]
@smilykoch @WimVanDerZijden 

Have a look at the PR, if you think it seems like a good solution #5 

cc: @marcuslindfeldt

**Comment by Flydiverny** [comment]
There's now a release v1.0.1 out with the fix.
