### ISSUE TITLE
select tab programatically

### ISSUE THREAD

**Issue by jonathanhotono** [marcuslindfeldt/react-web-tabs#10]
As mentioned on title, is there any way to select a certain tab programatically?
E.g 3 tabs, and certain interaction requires me to switch the active tab to 2nd/3rd from the default first ones.

**Comment by Flydiverny** [comment]
@jonathanhotono You should be able to do this by changing `defaultTab` property even if user has already selected another tab it would switch to the new default tab.

https://codesandbox.io/s/zqzpl8pnv3

**Edit:**
There's however no way to switch back to the tab which is already set as default tab

**Comment by jonathanhotono** [comment]
Ah great thanks, I wasn't too sure about the defaultTab whether it only acts on load or based on state changes.

**Comment by yunhan0** [comment]
In my project, default tab works in v1.0.0 but not v1.0.1

**Comment by pratikgupta2** [comment]
Can we control tab click and restrict user to navigate away from current tab with code ?

**Comment by Bhavya4274** [comment]
sa

**Comment by Bhavya4274** [comment]
dsadsad
