### ISSUE TITLE
Tab does not stay on current tab after refresh

### ISSUE THREAD

**Issue by thefolake** [marcuslindfeldt/react-web-tabs#15]
For example- I have 6 tabs, and I'm refreshing something on my last tab, it takes me back to the first/default tab after each refresh. 
Please can there be an option to allow remaining on the current/default tab after refresh?

**Comment by Flydiverny** [comment]
@thefolake I'd say thats outside the scope of the component. You should be able to implement that using your own logic. Setting the tab programmatically based on the URL or something you are using to track which tab you're at.
