### ISSUE TITLE
vertical tab not working

### ISSUE THREAD

**Issue by Moirafu** [marcuslindfeldt/react-web-tabs#7]
I tried to use your tabs in vertical style.But it remains in basic style.
my code is as follow:

```
<Tabs defaultTab="vertical-tab-one" vertical className="vertical-tabs">
                    <TabList >
                        <Tab tabFor="vertical-tab-one">Tab 1</Tab>
                        <Tab tabFor="vertical-tab-two">Tab 2</Tab>
                    </TabList>
                    <div>
                    <TabPanel tabId="vertical-tab-one">
                        <p>Tab 1 content</p>
                    </TabPanel>
                    <TabPanel tabId="vertical-tab-two">
                      <p>Tab 2 content</p>
                    </TabPanel>
                    </div>

                </Tabs>
```

and my result:
![image](https://user-images.githubusercontent.com/24188762/48241102-734f8100-e410-11e8-9c64-11ecc30566af.png)

**Comment by pavinduLakshan** [comment]
I have this same problem and came here to open an issue.Seems like this hasn't been solved yet.

**Comment by pavinduLakshan** [comment]
That is working..just add this before code..
import "react-web-tabs/dist/react-web-tabs.css";

**Comment by Flydiverny** [comment]
Thanks @pavinduLakshan 

Please see regarding styles in readme :)
https://github.com/marcuslindfeldt/react-web-tabs#styles

Feel free to create a new issue if you have any other problems!
