### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ravinleague** [marcuslindfeldt/react-web-tabs#9]
Uncaught TypeError: Cannot read property 'contains' of null
    at t._handleZoneBlur

**Comment by Flydiverny** [comment]
I'm sorry but this basically says nothing?

**Comment by marcuslindfeldt** [comment]
Closing this issue as this error does not seem to be related to this project. If you can provide more details we can reopen the issue.

**Comment by ravinleague** [comment]
Whenever I select a tab, i get this error in the developer console (Chrome). The error is - 
### Uncaught TypeError: Cannot read property 'contains' of null
at t._handleZoneBlur
However, when clicked, the tabs change and the css gets applied correctly.

**Comment by marcuslindfeldt** [comment]
Can you provide a minimal working example that reproduces the error?
